version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./homepage:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mariadb
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cs332e7
      MYSQL_USER: cs332e7
      MYSQL_PASSWORD: 2wJ3Nbfa
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/sql
    restart: always
    ports:
      - "3306:3306"
