version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./homepage:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mariadb
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
