version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./homepage:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mariadb
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: USERNAME
      MYSQL_USER: USERNAME
      MYSQL_PASSWORD: PASSWORD
    volumes:
      - ./sql:/sql
      - ./startup:/docker-entrypoint-initdb.d/:ro
    restart: always
    ports:
      - "3306:3306"
    # command: sh -c "mysql -h mariadb -u USERNAME -pPASSWORD < /sql/schema.sql; mysql -h mariadb -u USERNAME -pPASSWORD < /sql/insert.sql"
